name: Unit tests

on:
  push:
    branches:
      - 'main'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: |
            python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Run tests
      working-directory: ./app
      env:
        TESTING: True
      run: |
        pipenv run ./test.sh